/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#include "/h/bsberg/CacheLib2/cachelib/navy/serialization/gen-cpp2/objects_data.h"

#include <thrift/lib/cpp2/gen/module_data_cpp.h>


