/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#include "/h/bsberg/CacheLib2/cachelib/navy/serialization/gen-cpp2/objects_constants.h"

#include <thrift/lib/cpp2/gen/module_constants_cpp.h>


namespace facebook { namespace cachelib { namespace navy { namespace serialization {

}}}} // facebook::cachelib::navy::serialization
