/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#pragma once

#include <thrift/lib/cpp2/gen/module_metadata_h.h>
#include "/h/bsberg/CacheLib2/cachelib/navy/serialization/gen-cpp2/objects_types.h"


namespace apache {
namespace thrift {
namespace detail {
namespace md {
using ThriftMetadata = ::apache::thrift::metadata::ThriftMetadata;
using ThriftServiceContext = ::apache::thrift::metadata::ThriftServiceContext;
using ThriftService = ::apache::thrift::metadata::ThriftService;

template <>
class StructMetadata<::facebook::cachelib::navy::serialization::IndexEntry> {
 public:
  static void gen(ThriftMetadata& metadata);
};
template <>
class StructMetadata<::facebook::cachelib::navy::serialization::IndexBucket> {
 public:
  static void gen(ThriftMetadata& metadata);
};
template <>
class StructMetadata<::facebook::cachelib::navy::serialization::Region> {
 public:
  static void gen(ThriftMetadata& metadata);
};
template <>
class StructMetadata<::facebook::cachelib::navy::serialization::RegionData> {
 public:
  static void gen(ThriftMetadata& metadata);
};
template <>
class StructMetadata<::facebook::cachelib::navy::serialization::AccessStats> {
 public:
  static void gen(ThriftMetadata& metadata);
};
template <>
class StructMetadata<::facebook::cachelib::navy::serialization::AccessTracker> {
 public:
  static void gen(ThriftMetadata& metadata);
};
template <>
class StructMetadata<::facebook::cachelib::navy::serialization::BlockCacheConfig> {
 public:
  static void gen(ThriftMetadata& metadata);
};
template <>
class StructMetadata<::facebook::cachelib::navy::serialization::BigHashPersistentData> {
 public:
  static void gen(ThriftMetadata& metadata);
};
template <>
class StructMetadata<::facebook::cachelib::navy::serialization::BloomFilterPersistentData> {
 public:
  static void gen(ThriftMetadata& metadata);
};
} // namespace md
} // namespace detail
} // namespace thrift
} // namespace apache
