/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#pragma once

#include <thrift/lib/cpp2/gen/module_constants_h.h>

#include "/h/bsberg/CacheLib2/cachelib/navy/serialization/gen-cpp2/objects_types.h"

namespace facebook { namespace cachelib { namespace navy { namespace serialization {

struct objects_constants {

};

}}}} // facebook::cachelib::navy::serialization
