name: build-cachelib-centos-latest
on:
  schedule:
     - cron:  '30 5 * * 1,4'
jobs:
  build-cachelib-centos8-latest:
    name: "CentOS/latest - Build CacheLib with all dependencies"
    runs-on: ubuntu-latest
    # Docker container image name
    container: "centos:latest"
    steps:
      - name: "update packages"
        run: dnf upgrade -y
      - name: "install sudo,git"
        run: dnf install -y sudo git cmake gcc
      - name: "System Information"
        run: |
          echo === uname ===
          uname -a
          echo === /etc/os-release ===
          cat /etc/os-release
          echo === df -hl ===
          df -hl
          echo === free -h ===
          free -h
          echo === top ===
          top -b -n1 -1 -Eg || timeout 1 top -b -n1
          echo === env ===
          env
          echo === gcc -v ===
          gcc -v
      - name: "checkout sources"
        uses: actions/checkout@v2
      - name: "build CacheLib using build script"
        run: ./contrib/build.sh -j -v -T
